### ISSUE TITLE
同是HP 288 Pro G5 MT Business

### ISSUE THREAD

**Issue by elpx** [liuqqqhuan/HP-288PRO-G5-EFI#3]
CPU是i7-9700，安装界面和装好之后紫屏
有啥解决办法嘛？

**Comment by elpx** [comment]
![DD3BF3F208E71505C6304529AF8C1963](https://user-images.githubusercontent.com/53938224/148015533-b1a8ece1-38ae-4562-8580-89b69aff2329.png)
![image](https://user-images.githubusercontent.com/53938224/148015559-0ccda70f-72ad-45b7-9a7f-dce16fa381e3.png)

**Comment by liuqqqhuan** [comment]
b站搜索黑苹果紫屏幕修复，使用hackintool修改显卡的缓冲帧

**Comment by elpx** [comment]
> 
可以了！
第一次安装操作失败了，卡在代码页面
后来我删掉EFI，放了新的进去，再尝试了一次，我发现缓冲帧变成了0007（我需要的那个），只修改了接口类型。重启之后发现正常了！
